CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(191) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'disabled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE applications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    app_key VARCHAR(64) NOT NULL,
    platform VARCHAR(20) NOT NULL DEFAULT 'web',
    allowed_origins JSON NOT NULL,
    retention_days INT UNSIGNED NOT NULL DEFAULT 30,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_applications_app_key UNIQUE (app_key),
    CONSTRAINT fk_applications_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_applications_platform CHECK (platform = 'web'),
    CONSTRAINT chk_applications_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT chk_applications_retention CHECK (retention_days BETWEEN 1 AND 3650),
    INDEX idx_applications_owner (created_by, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE issues (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    application_id BIGINT UNSIGNED NOT NULL,
    fingerprint CHAR(64) NOT NULL,
    title VARCHAR(500) NOT NULL,
    error_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'unresolved',
    level VARCHAR(20) NOT NULL DEFAULT 'error',
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    event_count BIGINT UNSIGNED NOT NULL DEFAULT 1,
    affected_user_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    latest_event_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_issues_app_fingerprint UNIQUE (application_id, fingerprint),
    CONSTRAINT fk_issues_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT chk_issues_status CHECK (status IN ('unresolved', 'resolving', 'resolved', 'ignored')),
    CONSTRAINT chk_issues_level CHECK (level IN ('error', 'warning')),
    INDEX idx_issues_app_last_seen (application_id, last_seen_at DESC),
    INDEX idx_issues_app_status_last_seen (application_id, status, last_seen_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id CHAR(36) NOT NULL,
    application_id BIGINT UNSIGNED NOT NULL,
    issue_id BIGINT UNSIGNED NULL,
    schema_version SMALLINT UNSIGNED NOT NULL,
    type VARCHAR(30) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    received_at DATETIME(3) NOT NULL,
    environment VARCHAR(40) NOT NULL,
    release_name VARCHAR(100) NULL,
    session_id VARCHAR(64) NOT NULL,
    anonymous_id VARCHAR(64) NULL,
    user_id VARCHAR(100) NULL,
    trace_id VARCHAR(64) NULL,
    page_url VARCHAR(2048) NOT NULL,
    page_path VARCHAR(1024) NOT NULL,
    error_name VARCHAR(100) NULL,
    error_message VARCHAR(2000) NULL,
    http_method VARCHAR(16) NULL,
    http_url VARCHAR(2048) NULL,
    http_status SMALLINT UNSIGNED NULL,
    http_duration_ms DECIMAL(12, 3) NULL,
    http_outcome VARCHAR(20) NULL,
    payload JSON NOT NULL,
    context JSON NOT NULL,
    breadcrumbs JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_events_app_event UNIQUE (application_id, event_id),
    CONSTRAINT fk_events_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_issue FOREIGN KEY (issue_id) REFERENCES issues (id) ON DELETE SET NULL,
    CONSTRAINT chk_events_schema_version CHECK (schema_version > 0),
    CONSTRAINT chk_events_type CHECK (type IN ('page_view', 'error', 'http')),
    CONSTRAINT chk_events_http_status CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
    CONSTRAINT chk_events_http_duration CHECK (http_duration_ms IS NULL OR http_duration_ms >= 0),
    CONSTRAINT chk_events_http_outcome CHECK (http_outcome IS NULL OR http_outcome IN ('success', 'failure', 'aborted')),
    INDEX idx_events_app_type_occurred (application_id, type, occurred_at DESC),
    INDEX idx_events_issue_occurred (issue_id, occurred_at DESC),
    INDEX idx_events_app_release_occurred (application_id, release_name, occurred_at DESC),
    INDEX idx_events_app_user_occurred (application_id, user_id, occurred_at DESC),
    INDEX idx_events_app_http_status_occurred (application_id, http_status, occurred_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
